# Working with Data

## Understanding scalar and vector operations

In [1]:
import numpy as np

In [2]:
myVect = np.array(np.int16([1, 2, 3, 4]))

print(myVect + 1)
print(myVect - 1)
print(2 ** myVect)

[2 3 4 5]
[0 1 2 3]
[ 2  4  8 16]


In [3]:
a = np.array([1, 2, 3, 4])
b = np.array([2, 2, 4, 4])

print(a == b)
print(a < b)

[False  True False  True]
[ True False  True False]


In [4]:
a = np.array([True, False, True, False])
b = np.array([True, True, False, False])

print(np.logical_or(a, b))
print(np.logical_and(a, b))
print(np.logical_not(a))
print(np.logical_xor(a, b))

[ True  True  True False]
[ True False False False]
[False  True False  True]
[False  True  True False]


## Performing vector multiplication

In [5]:
print(myVect * myVect)
print(np.multiply(myVect, myVect))

[ 1  4  9 16]
[ 1  4  9 16]


In [6]:
print(myVect.dot(myVect))

30


## Understanding basic operations

In [7]:
A = np.array([[1, 1], [1, 0]])
B = np.array([[1, 0], [0, 1]])
C = A - B

print(C)

[[ 0  1]
 [ 1 -1]]


In [8]:
print(C * -2)

[[ 0 -2]
 [-2  2]]


## Performing matrix multiplication

In [9]:
X = np.array([[4, 5], [2, 4], [3, 3]])
b = [3, -2]

print(np.dot(X, b))

[ 2 -2  3]


In [10]:
B = np.array([[3, -2], [-2, 5]])

print(np.dot(X, B))

[[ 2 17]
 [-2 16]
 [ 3  9]]


## Glancing at advanced matrix operations

In [11]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(A.transpose())

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [12]:
 print(np.linalg.inv(A))

[[-4.50359963e+15  9.00719925e+15 -4.50359963e+15]
 [ 9.00719925e+15 -1.80143985e+16  9.00719925e+15]
 [-4.50359963e+15  9.00719925e+15 -4.50359963e+15]]


## Using vectorization effectively

In [13]:
y = np.array([44,21,37])
print (y)
print (y.shape)

[44 21 37]
(3,)


In [14]:
X = np.array([[1.1, 1, 545, 1],[4.6, 0, 345, 2],
              [7.2, 1, 754, 3]])
print (X)

[[  1.1   1.  545.    1. ]
 [  4.6   0.  345.    2. ]
 [  7.2   1.  754.    3. ]]


In [15]:
X = np.array([1.1, 1, 545, 1, 4.6, 0, 345, 2, 
              7.2, 1, 754, 3]).reshape(3,4)
print(X)

[[  1.1   1.  545.    1. ]
 [  4.6   0.  345.    2. ]
 [  7.2   1.  754.    3. ]]


# Exploring the World of Probabilities

## Operating on probabilities

In [16]:
Sixes = (1/6) * (1/6)
print(Sixes)

0.027777777777777776


In [17]:
SixAndOther = (1/6) * (1 - (1/6))
print(SixAndOther)

0.1388888888888889


In [18]:
OtherAndSix = (1/6) * (1 - (1/6))
print(OtherAndSix)

0.1388888888888889


In [19]:
OneSix = (1/6) + (1/6)
print(OneSix)

0.3333333333333333


## Conditioning chance by Bayes’ theorem

In [20]:
Female = 0.6 * 0.5 / 0.35
print(Female)

0.8571428571428572


In [21]:
IsIll = 0.99 * 0.01 / ((0.01 * 0.99) + (0.99 * 0.01))
print(IsIll)

0.5
